CREATE SCHEMA [MANASBHARATI];

CREATE TABLE [MANASBHARATI].[ADMIN]
(
USERID INT IDENTITY (1,1),
USERNAME NVARCHAR(100) UNIQUE,
PASSWORD NVARCHAR(12),
USER_IMG NVARCHAR(MAX),
STATUS BIT,
USERTYPE NVARCHAR( 16 ) NOT NULL,
CREATEDATE DATETIME
)

INSERT [MANASBHARATI].[ADMIN] VALUES('Admin','123','Content/images/useravtar.png',1,'Admin',CURRENT_TIMESTAMP);



CREATE TABLE [MANASBHARATI].[SLIDER] (
MAPID INT IDENTITY(1,1) NOT NULL,
TITLE NVARCHAR(500) NULL,
IMG NVARCHAR(250) NULL,
BTNNAME NVARCHAR(250) NULL,
URL NVARCHAR(MAX) NULL,
DISPLAYORDER INT,
CREATEDATE DATETIME,
UPDATEDATE DATETIME
)

CREATE TABLE [MANASBHARATI].[TESTIMONIAL] (
MAPID INT IDENTITY(100,1) NOT NULL,
NAME NVARCHAR(100),
TESTIMONIAL NVARCHAR(MAX),
IMG NVARCHAR(550) NULL,
STATUS int,
CREATEDATE DATETIME,
UPDATEDATE DATETIME
)


CREATE TABLE [MANASBHARATI].[ADMISSION] (
REGNO INT IDENTITY(100000,1) PRIMARY KEY,
ROLLNO INT,
SESSION NVARCHAR(100),
STUDNAME NVARCHAR(300),
MOBILE NVARCHAR(10),
EMAIL NVARCHAR(320),
AADHAR NVARCHAR(12),
DOB DATETIME,
GENDER NVARCHAR(1),
CASTE NVARCHAR(100),
ADMITTED_CLASS NVARCHAR(300),
SECTION NVARCHAR(10),
PHOTOGRAPH NVARCHAR(300),
FATHER_NAME NVARCHAR(300),
MOTHER_NAME NVARCHAR(300),
PARENTMOBILE NVARCHAR(10),
BLOODGROUP NVARCHAR(10),
PARENTINCOME NVARCHAR(100),
PRESENT_ADDRESS NVARCHAR(2000),
PERMANENT_ADDRESS NVARCHAR(2000),
CREATEDATE DATETIME,
UPDATEDATE DATETIME
)

CREATE TABLE [MANASBHARATI].[RESULT] (
MAPID INT IDENTITY(1,1),
REGNO INT,
ROLLNO INT,
CLASS NVARCHAR(300),
CLASS_SECTION NVARCHAR(10),
SUBJECTNAME NVARCHAR(100),
PERIODIC DECIMAL,
THEORY DECIMAL,
TERMEND NVARCHAR(10),
TOTAL DECIMAL,
TOTALMARKS DECIMAL,
PERCENTAGE DECIMAL,
CREATEDATE DATETIME,
UPDATEDATE DATETIME
)

CREATE TABLE [MANASBHARATI].[NOTICE] (
MAPID INT IDENTITY(1,1),
TITLE NVARCHAR(3000),
URL NVARCHAR(MAX),
MARKNEW BIT,
CREATEDATE DATETIME,
UPDATEDATE DATETIME
)


CREATE TABLE [MANASBHARATI].[GALLERY]
(
MAPID INT IDENTITY (1,1),
USER_IMG NVARCHAR(1200),
CREATEDDATE DATETIME
)

SELECT * FROM [MANASBHARATI].[ADMISSION]

update [MANASBHARATI].[RESULT] set termend='2' where mapid=2;

