
CREATE TYPE [IDEAL].[TypeBulkResult] AS TABLE(

	[REGNO] [INT] NULL,
	[ROLLNO] [INT] NULL,
	[CLASS] [NVARCHAR] (300) NULL,
	[CLASS_SECTION] [NVARCHAR] (10) NULL,
	[SUBJECTNAME] [NVARCHAR] (100) NULL,
	[PERIODIC] [DECIMAL] NULL,
	[THEORY] [DECIMAL] NULL,
	[TERMEND] [NVARCHAR] (10) NULL,
	[TOTAL] [DECIMAL] NULL,
	[TOTALMARKS] [DECIMAL] NULL,
	[PERCENTAGE] [DECIMAL] NULL
)
GO

